import {
  ArrowLeft,
  ArrowRightLeft,
  Ban,
  Banknote,
  Building2,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleMinus,
  CircleX,
  Clock,
  Copy,
  Crown,
  Dices,
  Eye,
  Flag,
  Gauge,
  Handshake,
  House,
  HousePlus,
  Info,
  Landmark,
  Link,
  LogIn,
  Lock,
  LogOut,
  Maximize,
  MessageCircle,
  Music,
  Play,
  Plug,
  RefreshCw,
  RotateCcw,
  Send,
  Server,
  Settings,
  ShoppingCart,
  SkipForward,
  Square,
  TicketCheck,
  TriangleAlert,
  Unlock,
  Users,
  Volume2,
  Wifi,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * Semantic action names. Several names may share one glyph (`cancel` and `close`), but a name
 * always means the same glyph everywhere; UI chrome asks for the meaning, not for a Lucide icon.
 */
export const ACTION_ICON_NAMES = [
  'settings', 'leave', 'forfeit',
  'close', 'cancel', 'unready', 'decline',
  'confirm', 'accept', 'ready',
  'start', 'retry', 'refresh', 'reset', 'playAgain',
  'join', 'back',
  'host', 'stopHost', 'configuredServer',
  'copy', 'send', 'chat',
  'roll', 'buy', 'build', 'buildHotel', 'skip',
  'bail', 'jailCard', 'sellToBank', 'propose',
  'view', 'sellHouse', 'reject',
  'offline', 'previous', 'next',
  // Player card statuses and counters (plan 03).
  'jail', 'bankrupt', 'house', 'hotel',
  // Dialogs, toasts and settings (plan 04).
  'warning', 'error', 'info', 'success', 'crown', 'trade', 'cash', 'players', 'clock', 'link', 'wifi',
  'fullscreen', 'volume', 'music', 'speed',
] as const;

export type ActionIconName = typeof ACTION_ICON_NAMES[number];

export const ACTION_ICONS = {
  settings: Settings,
  leave: LogOut,
  forfeit: Flag,
  close: X,
  cancel: X,
  unready: X,
  decline: X,
  confirm: Check,
  accept: Check,
  ready: Check,
  start: Play,
  retry: RefreshCw,
  refresh: RefreshCw,
  reset: RotateCcw,
  playAgain: RotateCcw,
  join: LogIn,
  back: ArrowLeft,
  host: Server,
  stopHost: Square,
  configuredServer: Plug,
  copy: Copy,
  send: Send,
  chat: MessageCircle,
  roll: Dices,
  buy: ShoppingCart,
  build: HousePlus,
  buildHotel: Building2,
  skip: SkipForward,
  bail: Unlock,
  jailCard: TicketCheck,
  sellToBank: Landmark,
  propose: Handshake,
  view: Eye,
  sellHouse: CircleMinus,
  reject: CircleX,
  offline: WifiOff,
  previous: ChevronLeft,
  next: ChevronRight,
  jail: Lock,
  bankrupt: Ban,
  house: House,
  hotel: Building2,
  warning: TriangleAlert,
  error: CircleAlert,
  info: Info,
  success: CircleCheck,
  crown: Crown,
  trade: ArrowRightLeft,
  cash: Banknote,
  players: Users,
  clock: Clock,
  link: Link,
  wifi: Wifi,
  fullscreen: Maximize,
  volume: Volume2,
  music: Music,
  speed: Gauge,
} satisfies Record<ActionIconName, LucideIcon>;

export function isActionIconName(value: string): value is ActionIconName {
  return Object.hasOwn(ACTION_ICONS, value);
}
