import {
  ArrowLeft,
  Ban,
  Building2,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleMinus,
  CircleX,
  Copy,
  Dices,
  Eye,
  Flag,
  Handshake,
  House,
  HousePlus,
  Landmark,
  LogIn,
  Lock,
  LogOut,
  MessageCircle,
  Play,
  Plug,
  RefreshCw,
  RotateCcw,
  Send,
  Server,
  Settings,
  ShoppingCart,
  SkipForward,
  Square,
  TicketCheck,
  Unlock,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * Semantic action names. Several names may share one glyph (`cancel` and `close`), but a name
 * always means the same glyph everywhere; UI chrome asks for the meaning, not for a Lucide icon.
 */
export const ACTION_ICON_NAMES = [
  'settings', 'leave', 'forfeit',
  'close', 'cancel', 'unready', 'decline',
  'confirm', 'accept', 'ready',
  'start', 'retry', 'refresh', 'reset', 'playAgain',
  'join', 'back',
  'host', 'stopHost', 'configuredServer',
  'copy', 'send', 'chat',
  'roll', 'buy', 'build', 'buildHotel', 'skip',
  'bail', 'jailCard', 'sellToBank', 'propose',
  'view', 'sellHouse', 'reject',
  'offline', 'previous', 'next',
  // Player card statuses and counters (plan 03).
  'jail', 'bankrupt', 'house', 'hotel',
] as const;

export type ActionIconName = typeof ACTION_ICON_NAMES[number];

export const ACTION_ICONS = {
  settings: Settings,
  leave: LogOut,
  forfeit: Flag,
  close: X,
  cancel: X,
  unready: X,
  decline: X,
  confirm: Check,
  accept: Check,
  ready: Check,
  start: Play,
  retry: RefreshCw,
  refresh: RefreshCw,
  reset: RotateCcw,
  playAgain: RotateCcw,
  join: LogIn,
  back: ArrowLeft,
  host: Server,
  stopHost: Square,
  configuredServer: Plug,
  copy: Copy,
  send: Send,
  chat: MessageCircle,
  roll: Dices,
  buy: ShoppingCart,
  build: HousePlus,
  buildHotel: Building2,
  skip: SkipForward,
  bail: Unlock,
  jailCard: TicketCheck,
  sellToBank: Landmark,
  propose: Handshake,
  view: Eye,
  sellHouse: CircleMinus,
  reject: CircleX,
  offline: WifiOff,
  previous: ChevronLeft,
  next: ChevronRight,
  jail: Lock,
  bankrupt: Ban,
  house: House,
  hotel: Building2,
} satisfies Record<ActionIconName, LucideIcon>;

export function isActionIconName(value: string): value is ActionIconName {
  return Object.hasOwn(ACTION_ICONS, value);
}
