import { mixHex } from '../../../design-system/tokens/contrast';
import { OTB_PALETTE } from '../../../design-system/tokens/palette';

/**
 * The color behind the canvas (before the first frame and past the tabletop edge): a table mid tone,
 * identical to the CSS token --color-scene-backdrop (75% oak over 25% grain color).
 */
export const SCENE_BACKDROP_OAK_SHARE = 0.75;
export const SCENE_BACKDROP = mixHex(OTB_PALETTE['table-oak'], OTB_PALETTE['table-oak-dark'], SCENE_BACKDROP_OAK_SHARE);

/**
 * Scene palette harmonization (plan 02 T02.16). The board frame, foundation, center field and sockets take
 * their hue from OTB_PALETTE (jade, ink, paper, gold) instead of the v1 teal / lime. Derived colors keep the
 * luminance of the v1 value they replace, so light surfaces stay light and the tile text stays readable;
 * only hue and saturation moved. Each derived value names its source; `boardVisualTokens.test.ts` checks
 * that the hue family and the luminance still match.
 */
export const SCENE_PALETTE_SOURCES = {
  boardFrame: 'jade-700',
  boardBaseEdge: 'jade-700',
  tileSocket: 'jade-700',
  boardTop: 'jade-600',
  airportField: 'jade-600',
  airportFieldDark: 'jade-600',
  boardCenter: 'jade-600',
  centerPath: 'jade-600',
  boardBase: 'ink-500',
  boardOuterAccent: 'paper-300',
} as const;

export const boardVisualTokens = {
  sceneBackground: SCENE_BACKDROP,
  boardBase: '#99897b',
  boardBaseEdge: '#0a3f33',
  boardFrame: OTB_PALETTE['jade-700'],
  boardTop: '#c5ebe2',
  boardCenter: '#8dd4b4',
  boardAccent: OTB_PALETTE['gold-400'],
  plazaBase: '#5f7e54',
  plazaGroundDetail: '#375d4d',
  plazaPath: '#d8e8df',
  plazaFountain: '#537f82',
  plazaFountainStone: '#888b83',
  plazaFountainRim: '#656d6b',
  plazaWater: '#25bfd0',
  plazaTree: '#3c9d5c',
  plazaTreeDark: '#315e3d',
  plazaTreeTrunk: '#6d5141',
  plazaBench: '#705544',
  plazaLamp: '#3f494a',
  plazaFlowerBed: '#a96a72',
  tileSurface: '#ffffff',
  tileUpperSpecial: '#ffffff',
  tileFooter: '#ffffff',
  tileDivider: '#111318',
  tileSocket: '#0e5847',
  tileChassis: '#737b79',
  tileChassisSpecial: '#5d6868',
  tileChassisHover: '#88918d',
  tileChassisSelected: '#8b8267',
  tileBorder: '#163a48',
  tileText: '#1c2527',
  selection: '#ffd21a',
  hover: '#fff1a4',
  house: '#23aa6b',
  houseDark: '#14734a',
  houseDoor: '#6c3d2c',
  houseWindow: '#d5f7f0',
  hotel: '#ed4e66',
  hotelDark: '#b82d42',
  hotelWindow: '#d8f5ff',
  hotelEntrance: '#ffd66a',
  jail: '#8171dc',
  jailBars: '#314454',
  chance: '#ef5a35',
  chanceDark: '#c4531b',
  chanceFace: '#e9b85d',
  chanceQuestion: '#f52d43',
  chanceQuestionSide: '#b51d46',
  chest: '#16c1ad',
  chestBody: '#0d887c',
  chestLid: '#21b49e',
  chestBand: '#e5aa2e',
  chestLatch: '#ffd96b',
  railroad: '#236fc9',
  railroadLight: '#d5eff4',
  railroadPlatform: '#a9d1d8',
  utility: '#168be5',
  utilityWater: '#19bdeb',
  utilityLight: '#c5f5f2',
  utilityBulb: '#ffd400',
  utilityBulbHighlight: '#fff7c7',
  utilityBulbRay: '#ffd400',
  utilitySocket: '#7a7f84',
  utilitySocketDark: '#555a60',
  utilityFaucet: '#111a22',
  utilityDrop: '#19bdeb',
  wheelSeparator: '#fff5d6',
  wheelRing: '#15504f',
  wheelHub: '#111a22',
  wheelPointer: '#fff7c7',
  expense: '#e9545e',
  expenseDark: '#9e2d3c',
  parkingCar: '#36aa63',
  parkingCarCyan: '#39c5dc',
  parkingCarOrange: '#ff8a25',
  parkingCarCream: '#fff0b3',
  parkingCarGreen: '#36aa63',
  parkingGlass: '#d7f2f4',
  parkingLane: '#fff8df',
  handcuffMetal: '#2d3940',
  handcuffMetalDark: '#182229',
  startSignFace: '#ffca24',
  startSignSide: '#8f4b2c',
  startSignText: '#1b2528',
  airportField: '#7acda7',
  airportFieldDark: '#379067',
  airportRunway: '#59616b',
  airportRunwayEdge: '#3f474f',
  airportMarking: '#ffffff',
  airportTaxiway: '#b3c9af',
  centerPath: '#a1dbc1',
  boardOuterAccent: '#f3e9da',
} as const;
