import type { Tile } from './types';

const tileState: Tile[] = [
  {
    streetName: 'Xuất Phát',
    tileType: 'start',
  },
  {
    streetName: 'Cà Mau',
    tileType: 'normal',
    color: 'brown',
    price: 60,
    rent: 2,
    rentTiers: [10, 30, 90, 160, 250],
    houseCost: 50,
  },
  {
    streetName: 'Khí Vận',
    tileType: 'chest',
  },
  {
    streetName: 'Bạc Liêu',
    tileType: 'normal',
    color: 'brown',
    price: 60,
    rent: 4,
    rentTiers: [20, 60, 180, 320, 450],
    houseCost: 50,
  },
  {
    streetName: 'Thuế Thu Nhập',
    tileType: 'expense',
    rent: 200,
  },
  {
    streetName: 'Ga Hà Nội',
    tileType: 'railroad',
    color: 'railroad',
    price: 200,
  },
  {
    streetName: 'Buôn Ma Thuột',
    tileType: 'normal',
    color: 'lightblue',
    price: 100,
    rent: 6,
    rentTiers: [30, 90, 270, 400, 550],
    houseCost: 50,
  },
  {
    streetName: 'Cơ Hội',
    tileType: 'chance',
  },
  {
    streetName: 'Cần Thơ',
    tileType: 'normal',
    color: 'lightblue',
    price: 100,
    rent: 6,
    rentTiers: [30, 90, 270, 400, 550],
    houseCost: 50,
  },
  {
    streetName: 'Hải Phòng',
    tileType: 'normal',
    color: 'lightblue',
    price: 120,
    rent: 8,
    rentTiers: [40, 100, 300, 450, 600],
    houseCost: 50,
  },
  {
    streetName: 'Nhà Tù / Thăm Tù',
    tileType: 'jail',
  },
  {
    streetName: 'Đà Lạt',
    tileType: 'normal',
    color: 'pink',
    price: 140,
    rent: 10,
    rentTiers: [50, 150, 450, 625, 750],
    houseCost: 100,
  },
  {
    streetName: 'Công Ty Điện',
    tileType: 'company',
    price: 150,
  },
  {
    streetName: 'Hội An',
    tileType: 'normal',
    color: 'pink',
    price: 140,
    rent: 10,
    rentTiers: [50, 150, 450, 625, 750],
    houseCost: 100,
  },
  {
    streetName: 'Huế',
    tileType: 'normal',
    color: 'pink',
    price: 160,
    rent: 12,
    rentTiers: [60, 180, 500, 700, 900],
    houseCost: 100,
  },
  {
    streetName: 'Ga Huế',
    tileType: 'railroad',
    color: 'railroad',
    price: 200,
  },
  {
    streetName: 'Mũi Né',
    tileType: 'normal',
    color: 'orange',
    price: 180,
    rent: 14,
    rentTiers: [70, 200, 550, 700, 900],
    houseCost: 100,
  },
  {
    streetName: 'Khí Vận',
    tileType: 'chest',
  },
  {
    streetName: 'Sa Pa',
    tileType: 'normal',
    color: 'orange',
    price: 180,
    rent: 14,
    rentTiers: [70, 200, 550, 700, 900],
    houseCost: 100,
  },
  {
    streetName: 'Nha Trang',
    tileType: 'normal',
    color: 'orange',
    price: 200,
    rent: 16,
    rentTiers: [80, 220, 600, 800, 1000],
    houseCost: 100,
  },
  {
    streetName: 'Bãi Đỗ Xe',
    tileType: 'parking',
  },
  {
    streetName: 'Vũng Tàu',
    tileType: 'normal',
    color: 'red',
    price: 220,
    rent: 18,
    rentTiers: [90, 250, 700, 875, 1050],
    houseCost: 150,
  },
  {
    streetName: 'Cơ Hội',
    tileType: 'chance',
  },
  {
    streetName: 'Quy Nhơn',
    tileType: 'normal',
    color: 'red',
    price: 220,
    rent: 18,
    rentTiers: [90, 250, 700, 875, 1050],
    houseCost: 150,
  },
  {
    streetName: 'Đà Nẵng',
    tileType: 'normal',
    color: 'red',
    price: 240,
    rent: 20,
    rentTiers: [100, 300, 750, 925, 1100],
    houseCost: 150,
  },
  {
    streetName: 'Ga Đà Nẵng',
    color: 'railroad',
    tileType: 'railroad',
    price: 200,
  },
  {
    streetName: 'Bãi Cháy',
    tileType: 'normal',
    color: 'yellow',
    price: 260,
    rent: 22,
    rentTiers: [110, 330, 800, 975, 1150],
    houseCost: 150,
  },
  {
    streetName: 'Hồ Tây',
    tileType: 'normal',
    color: 'yellow',
    price: 260,
    rent: 22,
    rentTiers: [110, 330, 800, 975, 1150],
    houseCost: 150,
  },
  {
    streetName: 'Công Ty Nước',
    tileType: 'company',
    price: 150,
  },
  {
    streetName: 'Phú Quốc',
    tileType: 'normal',
    color: 'yellow',
    price: 280,
    rent: 24,
    rentTiers: [120, 360, 850, 1025, 1200],
    houseCost: 150,
  },
  {
    streetName: 'Vào Tù',
    tileType: 'gojail',
  },
  {
    streetName: 'Phú Mỹ Hưng',
    tileType: 'normal',
    color: 'green',
    price: 300,
    rent: 26,
    rentTiers: [130, 390, 900, 1100, 1275],
    houseCost: 200,
  },
  {
    streetName: 'Thảo Điền',
    tileType: 'normal',
    color: 'green',
    price: 300,
    rent: 26,
    rentTiers: [130, 390, 900, 1100, 1275],
    houseCost: 200,
  },
  {
    streetName: 'Khí Vận',
    tileType: 'chest',
  },
  {
    streetName: 'Nguyễn Huệ',
    tileType: 'normal',
    color: 'green',
    price: 320,
    rent: 28,
    rentTiers: [150, 450, 1000, 1200, 1400],
    houseCost: 200,
  },
  {
    streetName: 'Ga Sài Gòn',
    color: 'railroad',
    tileType: 'railroad',
    price: 200,
  },
  {
    streetName: 'Cơ Hội',
    tileType: 'chance',
  },
  {
    streetName: 'Đồng Khởi',
    tileType: 'normal',
    color: 'blue',
    price: 350,
    rent: 35,
    rentTiers: [175, 500, 1100, 1300, 1500],
    houseCost: 200,
  },
  {
    streetName: 'Thuế Xa Xỉ',
    tileType: 'expense',
    rent: 75,
  },
  {
    streetName: 'Landmark 81',
    tileType: 'normal',
    color: 'blue',
    price: 400,
    rent: 50,
    rentTiers: [200, 600, 1400, 1700, 2000],
    houseCost: 200,
  },
];

// Tile indices that make up each buildable colour group. Owning every tile in a
// group is a "monopoly": it doubles base rent and unlocks building houses.
export const colorGroups: Record<string, number[]> = {
  brown: [1, 3],
  lightblue: [6, 8, 9],
  pink: [11, 13, 14],
  orange: [16, 18, 19],
  red: [21, 23, 24],
  yellow: [26, 27, 29],
  green: [31, 32, 34],
  blue: [37, 39],
};

export const BOARD_SIZE = 40;
export const START_TILE_INDEX = 0;
export const JAIL_TILE_INDEX = 10;
export const GO_TO_JAIL_TILE_INDEX = 30;
export const RAILROAD_TILE_INDICES = [5, 15, 25, 35] as const;
export const UTILITY_TILE_INDICES = [12, 28] as const;
export const CHEST_TILE_INDICES = [2, 17, 33] as const;
export const CHANCE_TILE_INDICES = [7, 22, 36] as const;

export default tileState;
